import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { globSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.dirname(fileURLToPath(import.meta.url))

/**
 * One entry per HTML file. `work/**` is generated by `scripts/generate-pages.mjs`
 * before dev and build, so this glob is read after those files exist — a
 * multi-page build needs every page on disk at config time, which is the trade
 * we accept in exchange for per-project meta tags in static HTML.
 */
const input = Object.fromEntries(
  ['index.html', ...globSync('work/**/index.html', { cwd: root })].map((file) => [
    file === 'index.html' ? 'main' : path.dirname(file).replace(/[/\\]/g, '-'),
    path.resolve(root, file),
  ]),
)

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss()],
  build: { rollupOptions: { input } },
})
